#+TITLE: Hamza Hamud
#+OPTIONS: toc:nil
#+INCLUDE: "./html-templates/preample.html" export html
#+HTML_HEAD_EXTRA: <style type="text/css">
#+HTML_HEAD_EXTRA: .title { display: none; }
#+HTML_HEAD_EXTRA: </style>


* About Me

Hi! I'm Hamza, I enjoy trying out different things suited to my tastes, currently that is just programming and cryptography.

For any inquiries, please contact me via [[mailto:info@adalresearch.com][email.]]
:SEPARATOR:
-----
:END:

* Posts
#+INCLUDE: "./posts/posts.org" :lines "3-"

:SEPARATOR:
-----
:END:

* Projects

** Current Projects
*** [[https://github.com/hhamud/Zuer][Zuer]]
A personal project for self teaching cryptography from its base primitives

** Completed Projects
*** [[https://github.com/hhamud/Noir-ts-mode][Noir ts mode]]
   An Emacs language major mode written in Emacs-lisp for the Noir smart contract language that uses the tree-sitter api, includes syntax highlighting.

*** [[https://github.com/hhamud/Noir-mode][Noir mode]]
   An Emacs language major mode written in emacs-lisp for the Noir smart contract language that includes syntax highlighting.

*** [[https://github.com/hhamud/tree-sitter-Noir][Tree-sitter-Noir]]
   Treesitter plugin for Noir language, (a ZK circuit writing language).

*** [[https://github.com/hhamud/sway-mode][Sway Mode]]
   An Emacs language major mode written in emacs-lisp for the sway smart contract language that includes syntax highlighting and integrations with forc, forc-lsp and forc-fmt.
