#+TITLE: Hamza Hamud
#+OPTIONS: toc:nil
#+INCLUDE: "./html-templates/preample.html" export html
#+HTML_HEAD_EXTRA: <style type="text/css">
#+HTML_HEAD_EXTRA: .title { display: none; }
#+HTML_HEAD_EXTRA: </style>


* About Me

Hello! My name is Hamza Hamud, and I am a software engineer with a deep interest in distributed computing and cryptography. I also hold a Masters in Chemical Engineering from the University of Sheffield.


** Interests:
- Beyond my professional work, I enjoy delving into various topics such as gastroentology, or whatever else comes to mind.

- For any inquiries, please contact me via [[mailto:self@hamzahamud.com][email.]]
:SEPARATOR:
-----
:END:

* Posts
#+INCLUDE: "./posts/posts.org" :lines "3-"

:SEPARATOR:
-----
:END:

* Projects

** Current Projects
*** [[https://github.com/hhamud/flop][Flop]]
   A lisp implementation written from scratch in rust.

** Completed Projects
*** [[https://github.com/hhamud/Noir-ts-mode][Noir ts mode]]
   An Emacs language major mode written in Emacs-lisp for the Noir smart contract language that uses the tree-sitter api, includes syntax highlighting.

*** [[https://github.com/hhamud/Noir-mode][Noir mode]]
   An Emacs language major mode written in emacs-lisp for the Noir smart contract language that includes syntax highlighting.

*** [[https://github.com/hhamud/tree-sitter-Noir][Tree-sitter-Noir]]
   Treesitter plugin for Noir language, (a ZK circuit writing language).

*** [[https://github.com/hhamud/llm-copilot][llm-copilot]]
   An Emacs based local ai pair programmer

*** [[https://github.com/hhamud/sway-mode][Sway Mode]]
   An Emacs language major mode written in emacs-lisp for the sway smart contract language that includes syntax highlighting and integrations with forc, forc-lsp and forc-fmt.

*** [[https://github.com/hhamud/ChatGPT-mode][ChatGPT Mode]]
   An Emacs major mode written in emacs-lisp for integrating with ChatGPT bypassing the api token limits

*** [[https://github.com/hhamud/Arima-Forecasting][Arima Forecasting]]
   A Personal Project that applies an advanced statistical technique to predict future electricity prices for the British Market.
